name: KeyBricks
description: "KeyBricks"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.1
  cached_network_image: ^3.3.1
  readmore: ^3.0.0

  # ✅ MUST be here
  equatable: ^2.0.5
  url_launcher: ^6.3.0
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  webview_flutter: ^4.7.0
  webview_flutter_android: ^4.4.0
  webview_flutter_wkwebview: ^3.10.0
  share_plus: ^7.2.2
  intl: ^0.18.1
  sms_autofill: ^2.4.0
  package_info_plus: ^8.0.0
  flutter_native_splash: ^2.3.10
  shared_preferences: ^2.2.2
  dropdown_button2: ^2.3.9





dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/images/house1.jpg
    - assets/images/house2.jpg
    - assets/images/house3.jpg
    - assets/images/splash_bg.jpg
    - assets/images/ic_launcher.png

flutter_native_splash:
  color: "#FFFFFF"   # background color only
 # image: assets/images/ic_launcher.jpg   # 👈 SHOW THIS INSTEAD OF ICON
  android: true
  ios: true

  android_12:
    color: "#FFFFFF"

