name: KeyBricks
description: "KeyBricks"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.1
  cached_network_image: ^3.3.1
  readmore: ^3.0.0
  equatable: ^2.0.5
  url_launcher: ^6.3.0
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  webview_flutter: ^4.7.0
  webview_flutter_android: ^4.4.0
  webview_flutter_wkwebview: ^3.10.0
  share_plus: ^7.2.2
  intl: ^0.18.1
  sms_autofill: ^2.4.0
  package_info_plus: ^8.0.0
  flutter_native_splash: ^2.3.10
  shared_preferences: ^2.2.2
  dropdown_button2: ^2.3.9
  image_picker: ^1.0.7
  flutter_image_compress: ^2.2.0
  video_compress: ^3.1.2
  image: ^4.1.3
  video_player: ^2.8.1
  flutter_launcher_icons: ^0.13.1
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/images/house1.jpg
    - assets/images/house2.jpg
    - assets/images/house3.jpg
    - assets/images/splash_bg.jpg
    - assets/images/ic_launcher.png

flutter_native_splash:
  android: true
  ios: true
  color: "#000000"
  android_12:
    color: "#000000"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/ic_launcher.png
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: assets/images/ic_launcher.png

fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Regular.ttf
      - asset: assets/fonts/Poppins-SemiBold.ttf
      - asset: assets/fonts/Poppins-Bold.ttf